### ISSUE TITLE
util needed?

### ISSUE THREAD

**Issue by jonasalmeida** [SBU-BMI/featurescape#4]
Do we need https://github.com/SBU-BMI/featurescape/blob/gh-pages/server.js#L5 ? It appears to be used only in https://github.com/SBU-BMI/featurescape/blob/gh-pages/server.js#L92 and https://github.com/SBU-BMI/featurescape/blob/gh-pages/server.js#L93 where parms.find  and parms.project by themselves would sufice. Trying to reduce number of dependencies as usual :-)

**Comment by tdiprima** [comment]
Ah.  Well, when writing output, parms.find prints "Object[]".  Not very useful!  Therefore, we need the util dependency, in order to inspect what the variable actually contains.

**Comment by jonasalmeida** [comment]
good point, what about, say, JSON.stringify(parms.find,null,3)

**Comment by tdiprima** [comment]
Good.  Thank you.  I'll change it.
